name = "opsgenie-filtered-schedule-ics"
type = "javascript"
zone_id = ""
account_id = ""
route = ""
workers_dev = true
compatibility_date = "2022-06-13"

[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"
